sudo: false
dist: trusty
language: rust
cache: cargo


rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"
  - CARGO_MAKE_URL="https://bintray.com/sagiegurari/cargo-make/download_file?file_path=cargo-make_v"

before_install:
  - curl -SsL $CARGO_MAKE_URL$(cargo search cargo-make | grep cargo-make | cut -d\" -f2) > $HOME/.cargo/bin/cargo-make
  - chmod 777 $HOME/.cargo/bin/cargo-make
  - export PATH=$HOME/.cargo/bin:$PATH

install:
  - cargo make build

script:
  - cargo make test

after_script:
  - cargo make audit
  - cargo make chandler

after_success:
  - cargo make codecov

deploy:
  provider: script
  script: cargo make publish -t $CRATES_IO_TOKEN
  on:
    tags: true
    repo: althonos/pruefung
    rust: stable

notifications:
  email:
  - althonosdev@gmail.com
