sudo: false
dist: trusty
language: rust
cache: cargo


rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"
  - CARGO_MAKE_RUN_CODECOV="true"

before_script:
  - if [[ ! -e "$HOME/.cargo/bin/cargo-make" ]]; then cargo install --debug cargo-make; fi
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo make ci-flow

notifications:
  email:
  - althonosdev@gmail.com
