sudo: true
dist: trusty
language: rust
cache: cargo

addons:
  apt:
    packages:
    - libssl-dev

rust:
  - stable
  - beta
  - nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"
  - RUST_BACKTRACE=1
  - CARGO_MAKE_RUN_CODECOV=true
  - SCCACHE_DIR="$HOME/.cargo/sccache"

before_install:
  - ci/install-cargo-make.sh

install:
  - cargo make ci-setup-flow

script:
  - cargo make ci-flow

deploy:
  provider: script
  script: cargo make publish-flow
  on:
    tags: true
    repo: althonos/pruefung
    rust: stable

notifications:
  email:
  - althonosdev@gmail.com
