sudo: false
dist: trusty
language: rust
cache: cargo


rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"
  - RUST_BACKTRACE=1
  - CARGO_MAKE_RUN_CODECOV=true

before_install:
  - cargo install -f --debug cargo-make

script:
  - cargo make ci-flow

after_success:
  - cargo make audit
  - cargo make chandler

deploy:
  provider: script
  script: cargo make publish -t $CRATES_IO_TOKEN
  on:
    tags: true
    repo: althonos/pruefung
    rust: stable

notifications:
  email:
  - althonosdev@gmail.com
