sudo: false
dist: trusty
language: rust
cache: cargo


rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

before_install:
  - if [[ ! -e "$HOME/.cargo/bin/cargo-make" ]]; then cargo install --debug cargo-make; fi
  - export PATH=$HOME/.cargo/bin:$PATH

install:
  - cargo make build

script:
  - cargo make test

after_script:
  - cargo make audit
  - cargo make chandler

# after_success:
#   - cargo make codecov

deploy:
  provider: script
  script: cargo make publish -t $CRATES_IO_TOKEN
  on:
    tags: true
    repo: althonos/pruefung
    rust: stable

notifications:
  email:
  - althonosdev@gmail.com
