sudo: false
dist: trusty
language: rust
cache: cargo


rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

before_install:
  - if [[ ! -e "$HOME/.cargo/bin/cargo-make" ]]; then cargo install --debug cargo-make; fi
  - export PATH=$HOME/.cargo/bin:$PATH

install:
  - cargo make build

script:
  - cargo make test

after_success:
  - cargo make codecov

notifications:
  email:
  - althonosdev@gmail.com
