sudo: false
dist: trusty
language: rust
cache: cargo


rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

before_script:
  - cargo install cargo-travis
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
  - althonosdev@gmail.com
