sudo: false
language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

before_script:
  - pip install travis-cargo --user
  - export PATH=$HOME/.local/bin:$PATH

after_success:
  - travis-cargo coverage --no-sudo
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
  - althonosdev@gmail.com
