[tasks.coverage]
alias = "coverage-tarpaulin"

[tasks.coverage-tarpaulin.linux]
args = ["tarpaulin", "--ciserver=travis-ci"]

[tasks.audit]
install_crate = "cargo-audit"
command       = "cargo"
args          = ["audit"]

[tasks.codecov]
dependencies = ["coverage"]

[tasks.chandler]
install_script = ["gem install chandler -n target/gems"]
command = "target/gems/chandler"
args = ["push", "--github=althonos/pruefung"]
