[tasks.coverage]
install_crate  = "cargo-tarpaulin"
command        = "cargo"
args           = ["tarpaulin"]
windows_alias  = "empty"
mac_alias      = "empty"
install_script = []
script         = []

[tasks.audit]
install_crate = "cargo-audit"
command       = "cargo"
args          = ["audit"]
