[tasks.coverage]
alias = "tasks.cargo-tarpaulin"

[tasks.ci-coverage]
install-crate = "cargo-tarpaulin"
command = "cargo"
args = ["tarpaulin", "--ciserver=travis-ci"]

[tasks.codecov]
dependencies = ["ci-coverage"]

[tasks.chandler]
install_script = ["gem install chandler -n target/gems"]
command = "target/gems/chandler"
args = ["push", "--github=althonos/pruefung"]
