[tasks.coverage]
install_crate  = "cargo-tarpaulin"
command        = "cargo"
args           = ["tarpaulin"]
windows_alias  = "empty"
mac_alias      = "empty"
install_script = []
script         = []

[tasks.audit]
install_crate = "cargo-audit"
command       = "cargo"
args          = ["audit"]

[tasks.codecov]
dependencies = ["coverage"]

[tasks.chandler]
install_script = ["gem install chandler -n target/gems"]
command = "target/gems/chandler"
args = ["push", "--github=althonos/pruefung"]
