[tasks.coverage]
alias = "coverage-tarpaulin-xml"

[tasks.coverage-tarpaulin-xml]
install_crate = "cargo-tarpaulin"
command = "cargo"
args = ["tarpaulin", "--out=Xml", "--ciserver=travis-ci"]

[tasks.chandler]
install_script = ["gem install chandler -n target/gems"]
command = "target/gems/chandler"
args = ["push", "--github=althonos/pruefung"]
