[tasks.coverage]
alias = "coverage-tarpaulin-xml"

[tasks.coverage-tarpaulin-xml]
install_script = ["curl -SsL https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh | bash"]
command = "cargo"
args = ["tarpaulin", "--out=Xml", "--ciserver=travis-ci"]

[tasks.chandler]
install_script = ["gem install chandler -n target/gems"]
command = "target/gems/chandler"
args = ["push", "--github=althonos/pruefung"]
